.TH mcctl 1

.SH NAME
mcctl \- control and configure mcctl wrapped Minecraft servers

.SH SYNOPSIS
.B mcctl
ingame_command [arguments] |
.B mcctl
command [arguments]

.SH DESCRIPTION
.B mcctl
is a control interface towards the mcctl service. Minecraft servers may be
given commands directly, or using some external commands such as making the
server
.B start
or
.B stop.


.SH BUILT-IN COMMANDS
.TP
.BR init
Starts mcctl as well as all autostarting instances.

.TP
.BR shutdown
Stops mcctl.

.TP
.BR list
Lists all available Minecraft instances.

.TP
.BR start
Starts a server instance. If no instance is specified, all available instances
are started.
.IP
.R usage:
mcctl
.B start
[server instance identifier]

.TP
.BR stop
Stops a server instance. If no instance is specified, all running instances
are stopped.
.IP
.R usage:
mcctl
.B stop
[server instance identifier]

.TP
.BR restart
Restarts a server instance. If no instance is specified, all running instances
are restarted.
.IP
.R usage:
mcctl
.B restart
[server instance identifier]

.TP
.BR edit
Use the editor specified by $EDITOR to modify the configuration for the given
instance. Falls back to the nano editor if $EDITOR is empty.
.IP
.R usage:
mcctl
.B edit
<instance>

.TP
.BR create
Creates a new server instance with the given name.
.IP
.R usage:
mcctl
.B create
<instance>

.TP
.BR delete
Delete a server instance.
.IP
.R usage:
mcctl
.B delete
<instance>

.TP
.BR backup
Create a world backup for the given instance. If no instance is given, all
instances are backed up.
.IP
.R usage:
mcctl
.B backup
[server instance identifier]

.TP
.BR log
Gets the last n log messages the given instance.
.IP
.R usage:
mcctl
.B log
<lines to print> <instance>

.TP
.BR status
Show whether a particular instance is running.
.IP
.R usage:
mcctl
.B status
[server instance identifier]

.TP
.BR import
Create an instance from a pre-existing world.
.IP
.R usage:
mcctl
.B import
<instance> <world directory>

.TP
.BR install-jar
Import a Minecraft server JAR file so mcctl instances can use it.
.IP
.R usage:
mcctl
.B install-jar
<jar file>
